"""Visor Public API integration."""

from visor_api.client import (
	VisorAPIError,
	VisorClient,
	VisorConnectionTimeoutError,
	VisorReadTimeoutError,
	VisorTimeoutError,
)
from visor_api.adapter import adapt_facets_response, adapt_listing, adapt_search_response
from visor_api.query import LISTING_EXPANSIONS, LISTING_FIELDS, VisorListingQuery
from visor_api.level1_query import (
	LEVEL1_FACETS,
	LEVEL1_FACET_SORT,
	LEVEL1_FACET_VALUE_LIMIT,
	LEVEL1_RECENT_SOLD_DAYS,
	Level1FacetQuery,
	build_level1_facet_query_plan,
	build_level1_trim_enrichment_query_plan,
)
from visor_api.level1_service import (
	Level1FacetCollection,
	Level1FacetResponseError,
	Level1TrimFacetBucket,
	Level1YearFacetResult,
	RetrievedLevel1Facet,
	collect_level1_facets,
)
from visor_api.level1_cache import CachedLevel1FacetResult, cached_level1_facets
from visor_api.level2_service import (
	LEVEL2_SEARCH_EXPANSIONS,
	LEVEL2_SEARCH_FIELDS,
	Level2Collection,
	Level2Exclusion,
	Level2ListingRecord,
	collect_level2_listings,
	level2_search_params,
)
from visor_api.level2_cache import CachedLevel2Result, cached_level2_collection
from visor_api.cache import CachedSearchResult, cached_listing_search
from visor_api.models import (
	APIModel,
	Dealer,
	FacetData,
	FacetMeta,
	FacetMetric,
	FacetResponse,
	FacetStats,
	FacetValue,
	ListingDetail,
	ListingDetailResponse,
	ListingSearchResponse,
	ListingSummary,
	Option,
	Pagination,
	PriceHistoryEntry,
	Pricing,
	PricingLineItem,
	RangeBucket,
	RangeFacet,
	Vehicle,
	VehicleBuild,
)


__all__ = [
	"VisorAPIError",
	"VisorClient",
	"VisorConnectionTimeoutError",
	"VisorReadTimeoutError",
	"VisorTimeoutError",
	"VisorListingQuery",
	"LISTING_EXPANSIONS",
	"LISTING_FIELDS",
	"LEVEL1_FACETS",
	"LEVEL1_FACET_SORT",
	"LEVEL1_FACET_VALUE_LIMIT",
	"LEVEL1_RECENT_SOLD_DAYS",
	"Level1FacetQuery",
	"build_level1_facet_query_plan",
	"build_level1_trim_enrichment_query_plan",
	"Level1FacetCollection",
	"Level1FacetResponseError",
	"Level1TrimFacetBucket",
	"Level1YearFacetResult",
	"RetrievedLevel1Facet",
	"collect_level1_facets",
	"CachedLevel1FacetResult",
	"cached_level1_facets",
	"LEVEL2_SEARCH_EXPANSIONS",
	"LEVEL2_SEARCH_FIELDS",
	"Level2Collection",
	"Level2Exclusion",
	"Level2ListingRecord",
	"collect_level2_listings",
	"level2_search_params",
	"CachedLevel2Result",
	"cached_level2_collection",
	"CachedSearchResult",
	"cached_listing_search",
	"APIModel",
	"Dealer",
	"FacetData",
	"FacetMeta",
	"FacetMetric",
	"FacetResponse",
	"FacetStats",
	"FacetValue",
	"ListingDetail",
	"ListingDetailResponse",
	"ListingSearchResponse",
	"ListingSummary",
	"Option",
	"Pagination",
	"PriceHistoryEntry",
	"Pricing",
	"PricingLineItem",
	"RangeBucket",
	"RangeFacet",
	"Vehicle",
	"VehicleBuild",
	"adapt_facets_response",
	"adapt_listing",
	"adapt_search_response",
]
